"""empty message

Revision ID: aef89c3a2a44
Revises: d0e35ea19b9c
Create Date: 2026-09-17 18:17:43.477384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef89c3a2a44'
down_revision: Union[str, Sequence[str], None] = 'd0e35ea19b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
