"""add rating field

Revision ID: 128351bc0d30
Revises: 3d29a49b0fe1
Create Date: 2026-09-16 16:22:36.012639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128351bc0d30'
down_revision: Union[str, Sequence[str], None] = '3d29a49b0fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'rating')
    # ### end Alembic commands ###
